// Generated by scripts/build-hero-manifest.mjs. Do not edit by hand.
// Add or remove files in public/images/product-hero/<collection>/ and rebuild.

export interface HeroSource {
  width: number;
  avif: string | null;
  webp: string | null;
}

/**
 * Slides carry no alt text on purpose. They sit behind the hero copy as
 * decoration, so the slider is hidden from assistive tech and the heading
 * carries the meaning. credits.json holds a description and the licence
 * record for humans.
 */
export interface HeroSlide {
  id: string;
  /** CSS object-position, used to keep the subject clear of the headline. */
  focal: string;
  /** Ascending by width. */
  sources: HeroSource[];
}

export const heroImages = {
  "home": [
    {
      "id": "home-01",
      "focal": "center 55%",
      "sources": [
        {
          "width": 768,
          "avif": "/images/product-hero/home/home-01-768.avif",
          "webp": "/images/product-hero/home/home-01-768.webp"
        },
        {
          "width": 1280,
          "avif": "/images/product-hero/home/home-01-1280.avif",
          "webp": "/images/product-hero/home/home-01-1280.webp"
        },
        {
          "width": 1920,
          "avif": "/images/product-hero/home/home-01-1920.avif",
          "webp": "/images/product-hero/home/home-01-1920.webp"
        }
      ]
    },
    {
      "id": "home-02",
      "focal": "center 60%",
      "sources": [
        {
          "width": 768,
          "avif": "/images/product-hero/home/home-02-768.avif",
          "webp": "/images/product-hero/home/home-02-768.webp"
        },
        {
          "width": 1280,
          "avif": "/images/product-hero/home/home-02-1280.avif",
          "webp": "/images/product-hero/home/home-02-1280.webp"
        },
        {
          "width": 1920,
          "avif": "/images/product-hero/home/home-02-1920.avif",
          "webp": "/images/product-hero/home/home-02-1920.webp"
        }
      ]
    },
    {
      "id": "home-03",
      "focal": "center 50%",
      "sources": [
        {
          "width": 768,
          "avif": "/images/product-hero/home/home-03-768.avif",
          "webp": "/images/product-hero/home/home-03-768.webp"
        },
        {
          "width": 1280,
          "avif": "/images/product-hero/home/home-03-1280.avif",
          "webp": "/images/product-hero/home/home-03-1280.webp"
        },
        {
          "width": 1920,
          "avif": "/images/product-hero/home/home-03-1920.avif",
          "webp": "/images/product-hero/home/home-03-1920.webp"
        }
      ]
    },
    {
      "id": "home-04",
      "focal": "center 45%",
      "sources": [
        {
          "width": 768,
          "avif": "/images/product-hero/home/home-04-768.avif",
          "webp": "/images/product-hero/home/home-04-768.webp"
        },
        {
          "width": 1280,
          "avif": "/images/product-hero/home/home-04-1280.avif",
          "webp": "/images/product-hero/home/home-04-1280.webp"
        },
        {
          "width": 1920,
          "avif": "/images/product-hero/home/home-04-1920.avif",
          "webp": "/images/product-hero/home/home-04-1920.webp"
        }
      ]
    },
    {
      "id": "home-05",
      "focal": "center 55%",
      "sources": [
        {
          "width": 768,
          "avif": "/images/product-hero/home/home-05-768.avif",
          "webp": "/images/product-hero/home/home-05-768.webp"
        },
        {
          "width": 1280,
          "avif": "/images/product-hero/home/home-05-1280.avif",
          "webp": "/images/product-hero/home/home-05-1280.webp"
        },
        {
          "width": 1920,
          "avif": "/images/product-hero/home/home-05-1920.avif",
          "webp": "/images/product-hero/home/home-05-1920.webp"
        }
      ]
    }
  ]
} satisfies Record<string, HeroSlide[]>;

export type HeroCollection = keyof typeof heroImages;
