const IMG = {
  puf1: '/images/products/sandwich-panels/puf-panel/PHOENIXX_WALL_PUF_PANEL1.jpg',
  puf9: '/images/products/sandwich-panels/puf-panel/PHOENIXX_WALL_PUF_PANEL9.jpg',
  puf19: '/images/products/sandwich-panels/puf-panel/PHOENIXX_WALL_PUF_PANEL19.jpg',
  pufMfg: '/images/products/sandwich-panels/puf-panel/Phoenix-PUF-Panel-Manufacturers6.jpg',
  pufTop: '/images/products/sandwich-panels/puf-panel/TOP-PUF-PANEL-MANUFACTURE-IN-INDIA.webp',
  pufProject: '/images/products/sandwich-panels/puf-panel/Phoenixx_infratech_Projects174.png',
  roof5: '/images/products/sandwich-panels/roofing-panel/PHOENIXX_ROOFING_PANEL5.jpg',
  roof8: '/images/products/sandwich-panels/roofing-panel/PHOENIXX_ROOFING_PANEL8.jpg',
  roof16: '/images/products/sandwich-panels/roofing-panel/PHOENIXX_ROOFING_PANEL16.jpg',
  roofPuf1: '/images/products/ROOFING PUF PANEL/PHOENIXX-ROOFING-PUF-PANELS1.jpg',
  roofPuf3: '/images/products/ROOFING PUF PANEL/PHOENIXX-ROOFING-PUF-PANELS3.jpg',
  roofPuf5: '/images/products/ROOFING PUF PANEL/PHOENIXX-ROOFING-PUF-PANELS5.jpg',
  pir1: '/images/products/sandwich-panels/pir-panel/PIR-Sandwich-FM-approved-Panel-1.png',
  pir6: '/images/products/sandwich-panels/pir-panel/PIR-Sandwich-FM-approved-Panel-6.jpg',
  pir8: '/images/products/sandwich-panels/pir-panel/PIR-Sandwich-FM-approved-Panel-8.jpg',
  rw1: '/images/products/sandwich-panels/RockWool-panel/PHOENIXX_ROCHWOOL_PANEL1.jpg',
  rw8: '/images/products/sandwich-panels/RockWool-panel/PHOENIXX_ROCHWOOL_PANEL8.jpg',
  ceil4: '/images/products/sandwich-panels/wall-ceiling-panel/PUF-Panel-False-Ceiling-4.jpg',
  ceil2: '/images/products/sandwich-panels/wall-ceiling-panel/Industrial-False-Ceiling-PUF-Panel-2.jpg',
  crCeil: '/images/products/cleanroom/ceiling/cleanroom-Manufacture-Supplier-in-Ahmedabad9.webp',
  crDoor: '/images/products/cleanroom/doors/Cleanroom-Door-Manufacturer-in-Ahmedabad-1.jpg',
  crPart: '/images/products/cleanroom/partition/Cleanroom-Partation-supplier-Manufacture-in-Gujarat1.jpg',
  fireDoor: '/images/products/doors/fire-door/TORDRIX_FIRE_DOOR1.webp',
  gallery1: '/images/projects/gallery/Phoenix-Infratech-Project-Pics23.jpg',
  gallery2: '/images/projects/gallery/PHOENIXX_WALL_PUF_PANEL19.jpg',
  gallery3: '/images/projects/gallery/Phoenixx_infratech_Projects189.jpg',
};

const explicitMap: Record<string, string> = {
  'rise-of-sustainable-peb-structures': IMG.gallery1,
  'optimizing-cold-storage-energy-efficiency': IMG.puf9,
  'cleanroom-design-best-practices': IMG.crCeil,
  'choosing-right-insulated-panel': IMG.puf1,
  'fire-safety-industrial-buildings': IMG.fireDoor,
  'cold-chain-logistics-india': IMG.pufProject,
  'turnkey-epc-project-delivery': IMG.gallery1,
  'industrial-doors-selection-guide': IMG.fireDoor,
  'what-is-puf-panel-how-does-it-work': IMG.pufTop,
  'puf-panel-vs-traditional-roofing-sheets': IMG.roofPuf1,
  'puf-vs-pir-vs-rockwool': IMG.pir1,
  'how-puf-panels-reduce-energy-costs-factories': IMG.roofPuf3,
  'puf-panel-thickness-guide-industrial-buildings': IMG.puf1,
  'puf-panels-cold-storage-pharma-applications': IMG.puf9,
  'puf-panel-installation-accessories': IMG.pufMfg,
  'puf-panel-installation-near-me': IMG.pufTop,
  'puf-panel-manufacturers-in-ahmedabad': IMG.pufMfg,
  'cold-storage-panel-manufacturers-ahmedabad': IMG.puf9,
  'cleanroom-panel-solutions-ahmedabad-pharma': IMG.crPart,
  'puf-panel-price-ahmedabad-2025-guide': IMG.puf1,
  'industrial-roofing-solutions-ahmedabad-gidc': IMG.roofPuf5,
  'puf-vs-pir-vs-rockwool-ahmedabad-climate': IMG.rw1,
  'puf-panel-manufacturers-in-gujarat': IMG.pufMfg,
  'jindal-puf-panel-price-list': IMG.puf19,
  'puf-panel-installation-contractors': IMG.gallery1,
  'puf-panel-wall-installation': IMG.puf1,
  'puf-panel-installation-cost': IMG.pufTop,
  'puf-panel-house': IMG.gallery3,
  'puf-panel-price-ahmedabad-2026-guide': IMG.puf19,
  'puf-panel-price-india-cost-per-sq-ft': IMG.pufTop,
  'cold-storage-construction-cost-india': IMG.puf9,
  'sandwich-panel-price-india-breakdown': IMG.puf1,
  'puf-panel-installation-cost-ahmedabad': IMG.pufMfg,
  'warehouse-construction-cost-puf-panels': IMG.gallery1,
  'pir-panel-price-vs-puf-panel': IMG.pir6,
  'cold-storage-cost-per-mt-india': IMG.pufProject,
  'cleanroom-construction-cost-india': IMG.crCeil,
  'industrial-shed-cost-puf-panels': IMG.roofPuf1,
  'puf-panel-vs-pir-panel-comparison': IMG.pir1,
  'puf-panel-vs-rockwool-panel': IMG.rw8,
  'sandwich-panel-vs-brick-wall-construction': IMG.puf1,
  'puf-panel-vs-eps-panel': IMG.puf19,
  'pir-panel-vs-mineral-wool-panel': IMG.pir8,
  'best-insulated-panel-for-cold-storage': IMG.puf9,
  'puf-panel-vs-glass-wool-insulation': IMG.rw1,
  'fire-resistant-panel-pir-vs-puf': IMG.pir6,
  'puf-panel-vs-rcc-construction': IMG.gallery1,
  'prefabricated-vs-conventional-construction': IMG.gallery3,
  'how-to-reduce-heat-in-industrial-shed': IMG.roofPuf3,
  'best-roofing-solution-factory-india': IMG.roof5,
  'how-to-build-cold-storage-step-by-step': IMG.puf9,
  'how-to-choose-right-insulated-panel': IMG.puf1,
  'how-to-reduce-electricity-cost-cold-storage': IMG.pufProject,
  'best-wall-material-for-warehouse': IMG.puf19,
  'industrial-insulation-guide-beginners': IMG.pufTop,
  'how-to-build-cleanroom-india': IMG.crPart,
  'warehouse-construction-guide-india': IMG.gallery1,
  'factory-roofing-problems-solutions': IMG.roofPuf5,
  'puf-panel-supplier-ahmedabad-guide': IMG.pufMfg,
  'cold-storage-construction-gujarat': IMG.puf9,
  'sandwich-panel-supplier-surat': IMG.puf1,
  'puf-panel-manufacturer-vadodara': IMG.pufTop,
  'pir-panel-supplier-rajkot': IMG.pir1,
  'industrial-panel-supplier-vapi': IMG.puf19,
  'puf-panel-ankleshwar-industrial-guide': IMG.roofPuf1,
  'best-puf-panel-supplier-dahej': IMG.pufMfg,
  'cleanroom-contractor-ahmedabad': IMG.crDoor,
  'warehouse-construction-company-gujarat': IMG.gallery3,
  'what-is-puf-panel-complete-guide': IMG.pufTop,
  'what-is-pir-panel-benefits-uses': IMG.pir6,
  'types-of-sandwich-panels-explained': IMG.puf1,
  'what-is-cold-storage-construction': IMG.puf9,
  'what-is-cleanroom-how-it-works': IMG.crCeil,
  'what-is-peb-structure': IMG.gallery1,
  'advantages-of-prefabricated-buildings': IMG.gallery3,
  'future-of-industrial-construction-india': IMG.roofPuf3,
  'benefits-of-insulated-panels': IMG.puf19,
  'why-puf-panels-best-for-india-climate': IMG.roofPuf5,
  'lifespan-of-puf-panels': IMG.pufTop,
  'puf-panel-price-ahmedabad': IMG.puf1,
  'best-puf-panel-brand': IMG.pufMfg,
  'top-puf-manufacturers-ahmedabad': IMG.pufMfg,
  'puf-panel-manufacturers-gujarat': IMG.pufTop,
  'puf-panel-price-list-ahmedabad': IMG.puf19,
  'puf-panel-ahmedabad': IMG.puf1,
  'puf-panel-contact-ahmedabad': IMG.pufMfg,
  'puf-panel-vadodara': IMG.pufTop,
  'puf-panel-near-me': IMG.puf1,
  'puf-panel-india': IMG.roofPuf1,
  'understanding-puf-sandwich-panels': IMG.puf19,
  'benefits-of-puf-wall-panels': IMG.puf1,
  'puf-roofing-panels-india-climate': IMG.roof5,
  'puf-panels-cold-storage': IMG.puf9,
  'puf-panels-gujarat-case-study': IMG.gallery1,
  'puf-panels-hospitality-industry': IMG.ceil4,
  'puf-panels-sustainable-construction': IMG.roofPuf3,
  'puf-ceiling-panels-commercial': IMG.ceil2,
  'puf-vs-traditional-material-cost': IMG.puf19,
  'future-of-puf-panels': IMG.pufTop,
  'puf-panels-maharashtra-industrial': IMG.roofPuf5,
  'puf-panels-rajasthan-energy-efficiency': IMG.roof8,
  'puf-panels-agriculture-mp': IMG.pufProject,
  'puf-panels-education-sector': IMG.gallery3,
  'puf-panels-soundproofing': IMG.rw8,
};

const DEFAULT_IMAGE = IMG.pufTop;

export function getBlogCoverImage(slug: string): string {
  return explicitMap[slug] || DEFAULT_IMAGE;
}
